export const WATCH_SEASONS = 'WATCH_SEASONS';
export const SET_SEASONS = 'SET_SEASONS';

export const WATCH_EPISODE = 'WATCH_EPISODE';
export const SET_EPISODE = 'SET_EPISODE';

export const WATCH_CHARACTER = 'WATCH_CHARACTER';
export const SET_CHARACTER = 'SET_CHARACTER';
